#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Build frontend
cd /app/angular
npm install
npm run build
cd /app

python /app/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
